### ISSUE TITLE
curl: (6) Could not resolve host: rancher.aws.private

### ISSUE THREAD

**Issue by CloudaYolla** [aws-quickstart/quickstart-eks-rancher#16]
Hi,

I deployed the QS solution to (to a new VPC, a new EKS cluster option), but the deployment test step fails. Any suggestions on how to find out the cause?

(The whole stack is successfully created on us-west-2 / Oregon, and DNS setting is the default one aws.private) 

```
[ec2-user@ip-10-0-144-228 ~]$ curl -k https://rancher.aws.private/
curl: (6) Could not resolve host: rancher.aws.private

```

This is the SSM Automation command status: 

Execution detail: hba-rancher-on-eks-v4-EKSStack-12IPK9HMJAD7R-RancherStack-

(Last 2 items in state pending since over 24 hours)

```
Step ID | Step # | Step name | Action | Status | Start time | End time
-- | -- | -- | -- | -- | -- | --
b62092c1-12a1-4397-886c-fbe78cf8a709 | 1 | CreateStack | aws:createStack | Success | Mon, 08 Feb 2021 13:23:30 GMT | Mon, 08 Feb 2021 13:26:57 GMT
b5335396-c510-4038-ba9a-24e1db6f91b6 | 2 | getInstanceId | aws:executeAwsApi | Success | Mon, 08 Feb 2021 13:26:57 GMT | Mon, 08 Feb 2021 13:26:58 GMT
28f9a629-e86f-410e-a78b-3c31ca9e721e | 3 | DownloadAndRunRancherInstallScript | aws:runCommand | Success | Mon, 08 Feb 2021 13:26:58 GMT | Mon, 08 Feb 2021 13:27:39 GMT
95930a99-9273-4478-be7d-d063c4101484 | 4 | CFNSignalEnd | aws:branch | Success | Mon, 08 Feb 2021 13:27:39 GMT | Mon, 08 Feb 2021 13:27:39 GMT
818bb215-603b-4119-bcf5-227868369511 | 5 | signalsuccess | aws:executeAwsApi | Success | Mon, 08 Feb 2021 13:27:39 GMT | Mon, 08 Feb 2021 13:27:40 GMT
61565343-ba3d-44b1-be84-53893d219bf2 | 6 | deleteStack | aws:deleteStack | Success | Mon, 08 Feb 2021 13:27:40 GMT | Mon, 08 Feb 2021 13:29:44 GMT
1d3120a0-b4fa-4f67-ab3c-0b85a041b781 | - | sleepend | aws:sleep | Pending | - | -
89bced20-258d-459b-b73e-0a8bcc813bed | - | signalfailure | aws:executeAwsApi | Pending | - | -
```

**Comment by awsandrewpark** [comment]
@CloudaYolla this issue is being investigated and a fix is in the works.  In the meantime, can you please confirm that you chose the "new VPC and new EKS" and also that you did not have to specify the VPC nor the CIDR?

**Comment by davmayd** [comment]
The deploy links for "new EKS cluster and new VPC" and "new EKS cluster and existing VPC" were reversed and have now been updated

**Comment by CloudaYolla** [comment]
Hi,
yes, the deployment links were wrong in the QS site, but I made sure I used the new VPC, new cluster option, from the workshop site. So, I didn't specify the CIDR ranges for VPC. 

This one: 
https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-entrypoint-new-vpc.template.yaml  

from Deployment guide: https://aws-quickstart.github.io/quickstart-eks-rancher/

**Comment by awsandrewpark** [comment]
@CloudaYolla the problem should be fixed now.  Can you please re-try the steps?

**Comment by davmayd** [comment]
This has been confirmed as resolved
