### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by sdahlbac** [aws-quickstart/quickstart-eks-rancher#20]
Deploy Rancher into a new VPC and new Amazon EKS cluster, Deploy Rancher into an existing VPC and a new Amazon EKS cluster and Deploy Rancher into an existing VPC and existing Amazon EKS cluster all point to the defunct `http://qs_launch_link/`

**Comment by davmayd** [comment]
Thanks! Fixed with this commit: https://github.com/aws-quickstart/quickstart-eks-rancher/commit/05c566be640cf24a4a85937ce2f947458ae6e38d
