### ISSUE TITLE
Stack referenced in documentation is not the same as the actual template in this repository

### ISSUE THREAD

**Issue by it-aofl** [aws-quickstart/quickstart-eks-rancher#21]
We are attempting to launch the stack titled "Deploy Rancher into an existing VPC and a new Amazon EKS cluster" in the documentation. This link points to a cloudformation stack (https://aws-quickstart.s3.us-east-1.amazonaws.com/quickstart-amazon-eks/templates/amazon-eks-entrypoint-existing-vpc.template.yaml) which contains several nested stacks and is far more comprehensive than the template pointed to from the "View Template" link (https://github.com/aws-quickstart/quickstart-eks-rancher/blob/main/templates/rancher.template.yaml). 

A notable immediate difference in the committed template rancher.template.yaml is single AZ, and appears less robust than the above mentioned cloudformation link. 

We would like to see all the templates committed to this repository if possible.

**Comment by davmayd** [comment]
The template included in the repository is used to deploy Rancher into an existing EKS cluster in an existing VPC. If you select either of the other options (new EKS cluster in a new VPC or new EKS cluster in an existing VPC), the EKS Quick Start (https://github.com/aws-quickstart/quickstart-amazon-eks) is deployed with the Rancher submodule enabled. The EKS Quick Start deploys a highly-available EKS cluster and then deploys the Rancher template into that cluster.
