### ISSUE TITLE
Parameter 'EKSClusterName' must match the pattern

### ISSUE THREAD

**Issue by imtms** [aws-quickstart/quickstart-eks-rancher#25]
There is a restriction : Parameter 'EKSClusterName' must match pattern ^EKS-[0-9a-zA-Z]{8}$

But there is no clear reminder before create CloudFormation Stacks.

A name that does not meet the pattern entered by yourself will cause errors and rollbacks after running the stacks for about an hour.

**Comment by imtms** [comment]
What is unreasonable is that if I enter the name that does not meet the pattern, there will be no error when I create stacks.

And it will report errors and rollbacks until it is executed for an hour.

If this rule is necessary, please verify before creating stacks, or clearly remind.

**Comment by davmayd** [comment]
I can't replicate the issue. If I try to deploy with a non-matching pattern it fails immediately. 
![image](https://user-images.githubusercontent.com/51335587/129607752-ab3182ee-a418-4530-858d-d8416d1c1671.png)
Which scenario are you launching? Existing EKS cluster and existing VPC, or something else?

**Comment by davmayd** [comment]
The REGEX has been removed

**Comment by cloudlady911** [comment]
You may have removed the regex from the stack definition but it still fails if the cluster is not named EKS-something.
