### ISSUE TITLE
It does not work!!

### ISSUE THREAD

**Issue by msaustral** [aws-quickstart/quickstart-eks-rancher#27]
Hi the template does not work!

Every time we try to run it it fail.

- if you place a custom cluster name it fail
- if you change the S3 bucket name it fail
- when you delete the stack on cloud formation it fail to delete and 2 childs are not deleted

we see there are people having problem since march but there is no answer!! is this project abandon?

**Comment by davmayd** [comment]
Hi @msaustral . Which option are you deploying? Are you deploying into a new EKS cluster, or an existing EKS cluster? If you're deploying into a new EKS cluster it first launches the https://github.com/aws-quickstart/quickstart-amazon-eks Quick Start, with Rancher as a submodule. If you're failing at autodetect that's occurring before the Rancher template is even launched.

**Comment by msaustral** [comment]
Hi the AWS quick start has an error on the couldformation template, we report it to AWS

**Comment by davmayd** [comment]
Understood. Which template are you launching?

**Comment by msaustral** [comment]
To solve the issue you must use eksctl template https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html

The template with issue is: https://aws-quickstart.github.io/quickstart-amazon-eks/ when you clic on Deploy Amazon EKS into a new VPC

**Comment by davmayd** [comment]
Does your stack even get to the Rancher stack, or does it fail beforehand? If it fails, please open an issue on the EKS Quick Start (https://github.com/aws-quickstart/quickstart-amazon-eks), the template is there (https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-entrypoint-new-vpc.template.yaml)

**Comment by msaustral** [comment]
Hi we could not even create the eks cluster, we did open a case with aws

**Comment by davmayd** [comment]
Thank you. I am closing this issue since it's an issue with the EKS Quick Start rather than the Rancher Quick Start. Feel free to open a new issue there if AWS Support can't get you squared away.
