### ISSUE TITLE
Is there anyway to directly access rancher console from my local browser, not using a RDP bastion host.

### ISSUE THREAD

**Issue by jaggerwang** [aws-quickstart/quickstart-eks-rancher#30]
There is a description in the [guide](https://aws-quickstart.github.io/quickstart-eks-rancher/#_post_deployment_steps) said that I need to deploy an RDP bastion host into a public subnet of the VPC that hosts the EKS worker nodes, but it just one sentence with no details. And if I don't want to deploy an RDP bastion host, how can I directly access rancher console from my local browser using my custom domain name `rancher.basic.ai`.

I already got the ingress controller's external ip in a bastion host, which was deployed when creating the EKS rancher stack , but it is an internal ip.

```
$ kubectl get service ingress-nginx-controller --namespace=ingress-nginx
NAME                       TYPE           CLUSTER-IP       EXTERNAL-IP                                                                     PORT(S)                      AGE
ingress-nginx-controller   LoadBalancer   172.20.176.154   aae95e6c3321846fb9cb11bf0e92616f-39de84d734b3c4c7.elb.us-west-2.amazonaws.com   80:30133/TCP,443:30745/TCP   33m
$ ping aae95e6c3321846fb9cb11bf0e92616f-39de84d734b3c4c7.elb.us-west-2.amazonaws.com
PING aae95e6c3321846fb9cb11bf0e92616f-39de84d734b3c4c7.elb.us-west-2.amazonaws.com (10.0.31.95) 56(84) bytes of data.
```

**Comment by jaggerwang** [comment]
I solved it by myself, I created an internet-facing NLB (network loading balancer), and resolve my domain `rancher.basic.ai` to the public ip of this NLB, or cname to the NLB's domain.

**Comment by gabrielibagon** [comment]
@jaggerwang Could you elaborate on the steps you took to implement this? I would like to access the rancher UI from a local browser.

Here are the steps I've taken so far:

1. Create an NLB with the following options:
    a. Internet-facing
    b. IPv4 address type
    c. Select the same VPC as EKS-Rancher stack
    d. Select a single public subnet
    e. IPv4 assigned by AWS
    f. Listener - TCP Port 80 with a newly created target group that includes the BastionEKS instance

I'm unsure what the next steps would be after this in order to "resolve the domain `rancher.basic.ai` to the public ip of this NLB". Do you have any guidance here?
